### PR TITLE
Virtual environment slides

### PR DESCRIPTION
**Pull request by PiRK**

### CODE REVIEW

**Comment by PiRK** [comment]
I forgot to mention Anaconda, WinPython & cie.

**Comment by kif** [comment]
Beside  this it looks good to me. 

When are we speaking about binary distribution and manylinux1 ?

**Comment by PiRK** [comment]
The issue I have with python 3 venv on my debian 8 is : 
```
knobel@linsimak:~/venvs$ python3 -m venv myvenv3
Error: Command '['/users/knobel/venvs/myvenv3/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1

```

This command line only works with option `--without-pip`.

**Comment by PiRK** [comment]
After installing the `python3-venv` package, it works.

**Comment by kif** [comment]
On Mon, 13 Mar 2017 02:39:09 -0700
Pierre Knobel <notifications@github.com> wrote:

> The issue I have with python 3 venv on my debian 8 is : 
> ```
> knobel@linsimak:~/venvs$ python3 -m venv myvenv3
> Error: Command '['/users/knobel/venvs/myvenv3/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1
> 
> ```
> 
> This command line only works with option `--without-pip`.

It works for me and on scisoft13:

It failed on scisoft12 ... in a similar way to your computer. The
ensurepip is missing which is provided by python3-venv.

Conclusion, python3-venv is needed to use venv in debian8 environment.

-- 
Jérôme Kieffer
tel +33 476 882 445

**Pull request merged**
